apiVersion: apps/v1
kind: Deployment
metadata:
  name: item-service
  namespace: cesieats-services
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: item-service
  template:
    metadata:
      labels:
        app: item-service
    spec:
      containers:
        - name: item-service
          image: kilme/item-service:$IMAGE_VERSION
          env:
          - name: DB_USERNAME
            valueFrom: 
              secretKeyRef:
                name: mongo-creds
                key: username
          - name: DB_PASSWORD
            valueFrom: 
              secretKeyRef:
                name: mongo-creds
                key: password
          resources:
            limits:
              memory: "512Mi"
              cpu: "250m"
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: service-item
  namespace: cesieats-services
spec:
  selector:
    app: item-service
  ports:
    - name: http
      protocol: TCP
      port: 3000
      nodePort: 30109
  type: NodePort